manifest:
  remotes:
    - name: custom_zmkfirmware
      url-base: https://github.com/a-wark
  projects:
    - name: custom_zmkfirmware
      remote: zmk
      revision: custom
      import: app/west.yml
  self:
    path: config
