manifest:
  remotes:
    - name: custom_zmkfirmware
      url-base: https://github.com/a-wark
    - name: tri-state
      url-base: https://github.com/dhruvinsh
    - name: m165437
      url-base: https://github.com/M165437
  projects:
    - name: zmk
      remote: custom_zmkfirmware
      revision: studio
      import: app/west.yml
    - name: zmk-tri-state
      remote: tri-state
      revision: main
    - name: nice-view-gem
      remote: m165437
      revision: main
  self:
    path: config
